<a href="https://colab.research.google.com/github/Kovidapunj/Exploratory-data-analysis-using-python/blob/main/experiment_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Experiment 8
## Title - tool for EDA - study of Numpy library
## Name - Kovida Punj
## PRN - 25070123063
## batch - E&TC A3
## date - 18/02/2026


In [ ]:
# faster than lists
# used for numerical computation
# base for pandas


In [5]:
# declaration of Numpy
import numpy as np

a = np.array([10,20,30,40])
b = np.array([[1,2,3],[4,5,6]])
print(a)
print(b)

[10 20 30 40]
[[1 2 3]
 [4 5 6]]


In [6]:
#dimension of array
print(a.ndim)
print(b.ndim)

1
2


In [7]:
print(a.shape)
print(b.shape)

(4,)
(2, 3)


In [8]:
print(a.dtype)

int64


In [10]:
#In built functions using Numpy
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.arange(1,10,2) #like range function

array([1, 3, 5, 7, 9])

In [18]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [19]:
print( b * 2)
print(a + 5)


[[ 2  4  6]
 [ 8 10 12]]
[15 25 35 45]


In [21]:
print(b)

[[1 2 3]
 [4 5 6]]


In [22]:
np.mean(a)

np.float64(25.0)

In [24]:
np.median(a)

np.float64(25.0)

In [26]:
np.mean(b)


np.float64(3.5)

In [27]:
np.median(b)


np.float64(3.5)

In [28]:
np.max(a)

np.int64(40)

In [30]:
np.min(a)

np.int64(10)

In [31]:
np.sum(a)

np.int64(100)